---
title: Recomendações
---

Para a realização da FTPA 2026, algumas das recomendações sugeridas na FTPA 2025 forma seguidos como, por exemplo, a inclusão de alunos da comissão organizadora, uma maior divisão de tarefas junto aos membros da comissão e o estabelecimento de uma parceria com a Prefeitura de Limeira para o fornecimento de transporte para algumas escolas da cidade. Além disso, houve uma melhoria na logística das trilhas e do processo do envio da documentação para o pagamento das diárias para os monitores, ambos em virtude dos aprendizados adquiridos durante a implmentação e execução da FTPA 2025. Houve também melhorias no campus, principalmente a pintura de prédios como a biblioteca, o pavilhão e o prédio ao lado da administração. O número de atrações também aumentou, principalmente em virtude da apresentação dos laboratórios de pesquisa, o que levou também a um aumento da participação da comunidade interna.

Algumas recomendação para a próxima edição são:

## Redução de custo com segurança adicional

O cálculo do número de agentes adicionais é feito baseado no número total de visitantes. No entanto, o FTPA é um evento que as visitas são distribuídas ao longo do dia. Dessa forma, é importante mencionar esse fato para a contratação do serviço na próxima edição. Como verificado nas edições do FTPA, dois agentes adicionais nos pareceram suficientes.


## Convênio com prefeitura de Limeira

Ampliar a colaboração da prefeitura de Limeira com o fornecimento de transporte para as escolas da cidade permitirá aumentar muito o número de visitantes. Tivemos o interesse de mais escolas de Limeira mas que não puderam vir por falta de transporte. Estabeler um convênio e organizar o transporte com as escolas com mais antecedência contribuirão para uma melhor organização do evento.

## Parceria com o Cotil 

Apesar da divulgação do evento para a diretoria acadêmica do Cotil, não houve participação de alunos do Cotil no evento. Esse é um ponto que requer bastante atenção uma vez que o Cotil divide o campus com a FT e o acesso ao evento não tem obstáculos como outras escolas de Limeira.


## Logística

O processo de levar os grupos para as dinâmicas depende do horário de chegada das escolas. Sem esse horário, a organização tem que lidar com a incerteza da quantidade de alunos que estarão presentes em determinado horário. Solicitar junto as escolas, no formulário de inscrição os horários previstos de chegada pode ajudar nessa organização.

Pode ser preciso também discutir outros formatos para o evento, além das trilhas obrigatórias, a fim de melhorar a visitação.

Na FTPA 2026 foram usados rádios de comunicação pela equipe da logísitica, o que facilitou a organização dos grupos. Recomendamos usar os rádios novamente nas edições futuras.

## Documentação financeira 

Solicitar com mais antecedência a documentação necessária para o pagamento das ajudas de custos para os montiores para que o processo de empenho pagamento esteja pronto antes do dia do evento.


## Melhorias no campus

A constante melhoria do campus, seja ela para a visitação da comunidade externa, seja ela para o uso da comunidade de interna, deve ser sempre buscado pela Diretoria da FT e pela prefeitura do campus. 

## Ampliação da participação da comunidade interna

A FT de Portas Abertas beneficia a própria FT. Ações para aumentar a adesão da comunidade interna devem ser implantadas para expandir o número de atrações no evento e aproximar a FT da comunidade externa. Por exemplo, aumentar a participação de laboratórios de pesquisa deve ser uma meta para 2027.

## Acompanhamento e avaliação do impacto do evento

Estabelecer mecanismos sistemáticos de acompanhamento e avaliação do impacto do FTPA é fundamental para que ela atinja seus objetivos. A partir da coleta e análise de dados, como a percepção dos visitantes, a influência do evento na escolha dos cursos e a evolução do número de inscritos e ingressantes, será possível mensurar a eficácia da FTPA enquanto ação de divulgação institucional e de fortalecimento da graduação.

Enviamos um formulário para as escolas que participaram do evento. No entanto, apenas uma escola de Iracemápolis respondeu. A avaliação da escola foi positiva indicando que o evento foi excelente, que os pontos fortes foram "Organização, pontualidade, comprometimento, didática" e que os pontos a serem melhorados envolvia a "sinalização dos locais". 

Para a próxima edição, pretendemos manter o envio do formulário, alterando também as questões como indicado [aqui](questionario-1.txt). 

Como avaliação longitudinal para o monitoramento de ingressantes:  Identificar, junto aos alunos calouros se a FT de Portas Abertas foi um fator relevante na decisão dos ingressantes. Para isso, podem ser usados, por exemplo, questionários já existentes da FT e que já são aplicados para calouros no dia da matrícula. Uma sugestão de questionário pode ser visto [aqui](./questionario-2.txt).
