project:
  type: book

book:
  title: "FT de Portas Abertas 2025"
  author: "Comissão organizadora"
  date: "01/03/2025"
  chapters:
    - index.qmd
    - organizacao/organizacao.qmd
    - motivacao/motivacao.qmd
    - planejamento/planejamento.qmd
    - custos/custos.qmd
    - atividades/atividades.qmd
    - vistantes/visitantes.qmd
    - recomendacoes/recomendacoes.qmd
    - agradecimentos/agradecimentos.qmd
     
format:
  html:
    lang: pt
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    colorlinks: true
    keep-tex: true