project:
  type: website
  preview: 
    port: 4321
  
  
website:
  title: "*FT Portas Abertas*"
  site-url: https://www.ft.unicamp.br
  navbar:
    logo: /logo-FT/logo-com-nome.png
    left:
      - href: organizacao/organizacao.qmd
        text: Organização     
      - href: atividades/atividades.qmd
        text: Atividades
      - href: localizacao/localizacao.qmd
        text: Como chegar
    tools:
      - icon: instagram
        href: http://instagram.com/ft_unicamp

  page-footer:
    "FT de Portas Abertas 2025"

format:
  html:
    lang: pt
    page-layout: full
    css: styles.css
    toc: true



