project:
  type: book
  output-dir: docs

book:
  title: "FT de Portas Abertas"
  author: "Comissão organizadora"
  date: "07/30/2026"
  chapters:
    - index.qmd
    - part: "Edição 2025"
      chapters:
        - 2025/index.qmd
        - 2025/organizacao/organizacao.qmd
        - 2025/motivacao/motivacao.qmd
        - 2025/atividades/atividades.qmd
        - 2025/planejamento/planejamento.qmd
        - 2025/custos/custos.qmd
        - 2025/visitantes/visitantes.qmd
        - 2025/recomendacoes/recomendacoes.qmd
        - 2025/agradecimentos/agradecimentos.qmd
        - 2025/consideracoes/consideracoes.qmd
    - part: "Edição 2026"
      chapters:
        - 2026/index.qmd
        - 2026/organizacao/organizacao.qmd
        - 2026/motivacao/motivacao.qmd
        - 2026/atividades/atividades.qmd
        - 2026/planejamento/planejamento.qmd
        - 2026/custos/custos.qmd
        - 2026/visitantes/visitantes.qmd
        - 2026/recomendacoes/recomendacoes.qmd
        - 2026/agradecimentos/agradecimentos.qmd
        - 2026/consideracoes/consideracoes.qmd
    

format:
  html:
    lang: pt
    page-layout: full
    theme: cosmo
    css: styles.css
    toc: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    colorlinks: true
    keep-tex: true