---
title: Público-alvo
---

A *FT de Portas Abertas* tem como público-alvo principalmente **jovens que estão cursando o ensino médio** e que estão na fase da escolha de um curso universitário. 

De acordo com [dados de 2023](https://qedu.org.br/municipio/3526902-limeira/censo-escolar) do portal de dados educacionais [QEdu](https://qedu.org.br/), Limeira teve mais de **3000** estudantes matriculados na 3^o^ ano do Ensino Médio, sendo 2654 matrículas 3a seria de 25 escolas públicas e 562 matrículas de 18 escolas particulares. Para esses estudantes, a *FT de Portas Abertas* apresentará opções de cursos gratuitos, de qualidade e associados a áreas muito relevantes atualmente e que estão disponíveis na cidade de Limeira.

Além de estudantes do Ensino Médio, a *FT de Portas Abertas* também pretende alcançar a **população de forma geral**, atingindo, por exemplo, os familiares desses estudantes, a fim de divulgar atividades de pós-graduação, de pesquisa e de extensão que são oferecidos pela Faculdade de Tecnologia.

