---
title: Agradecimentos
---

Gostaríamos de agradecer os professores e funcionários da FT que contribuíram direta ou indiretamente para o FT de Portas Abertas 2026. Um agradecimento especial também aos alunos listados a seguir que, sem a participação deles, o evento não teria sido possível.

1. Adriano Baumgarte Bassani Filho
2. Alexandre Oscar Da Silva
3. Amanda Scaione
4. Ana Julia Vilas Boas
5. Anahita Albuquerque Santos
6. Andrezza Hellen Batista da Silva
7. Andrey Moura Gouvea
8. Antonio Carlos Rosendo da Silva
9. Auriane Nayara da Silva
10. Bárbara Beatriz Milani
11. Bianca Silva da Nobrega
12. Bianca Yukari Oshiro
13. Bruno dos Santos Bezerra
14. Carlos Daniel Nunes de Abreu
15. Cecilia Bumba Luango
16. Celso Kaique Lima Lira
17. Cicero Eduardo Campos Leite dos Santos
18. Dandara Melissa Alves
19. Daniel Hiroshi Yamaguti
20. Daniel Matias de Souza Nunes
21. Daniel Rodrigo Vicente de Oliveira
22. Danilo de Freitas Marques
23. Eduardo de Andrade Paziani Kouguem
24. Eduardo Junqueira Possan
25. Emanuel Elias Sanches da Costa
26. Felipe Silva Araújo
27. Felipe Vieira Conway Baccarat
28. Fernanda Souza Pedreira
29. Gabriel Cerqueira Pires
30. Gabriel Gato Piragini Santana
31. Gabriel Pereira de Oliveira
32. Gabriel São Martinho da Silva
33. Gabriela Maura Rodrigues
34. Gabriela Vieira Gonçalves
35. Giovana Fortes Vitale
36. Giovani Manoel da Silva
37. Giovanni da Silva Virginio Brandão
38. Guilherme Kauã Batista da Silva
39. Hyago Cristiano Conceição
40. Iara Soares dos Santos
41. Iris Bryan
42. Isadora Bonfim de Sousa Santos
43. Izabela da Silva Lopes
44. Jean Victor Duarte Pedro
45. Jhenyffer Cristina dos Santos
46. João Pedro Pina Garcez
47. João Pedro Silva Ferreira
48. João Pedro Vernaschi Zampronio
49. Jonathan Jeronir da Silva
50. Joyce Soares Martins
51. Juan Carlos Rezende Canha
52. Julia Almeida Malta
53. Julia Christina Fraga de Brito
54. Julia Coqueiro Ho
55. Julia Dias Luz
56. Julya Paes de Souza
57. Kaio Henrique Caraceli
58. Kayan Aryel Silva de Souza
59. Kaylane Borges Buzelim
60. Lara Trabachini
61. Larissa Helena Franceli
62. Laura Rodrigues Russo
63. Leonardo Bonfa Schroeder
64. Leonardo Hideaki Sasaki Kopczynski
65. Lilia Cordeiro França
66. Luca Calçada Dolim Marote
67. Lucas da Silva Domiciano
68. Luíz Carlos Assunção e Sá
69. Luiz Guilherme Grip Gonzaga
70. Luiza Brum Pires de Brito
71. Luiza Guimarães Bonacio
72. Luiza Silva Venâncio
73. Maria Julia Simionato Salvador
74. Maria Luisa A. Agustinho Sampaio da Silva
75. Maria Teresa Albertoni Mercadante
76. Marcelo Meloni Masson
77. Mateus Domingos
78. Mariana Nogueira Neves
79. Matheus Bernardes Rafael Arruda
80. Matheus Placideli Reghini
81. Mauricio Yago Miranda dos Santos
82. Milton Edson Schutz
83. Murilo Bertolini Montoni
84. Murilo de Carvalho Ximenes
85. Murilo Leite da Silva
86. Nathan Augusto Gonçalves da Rocha
87. Nicolas Yuri da Silva Santos
88. Orlando Nogueira São Pedro
89. Otávio Andrade Freitas Moraes
90. Otavio Coffani Rumachella
91. Paloma Camili Nogueira dos Santos
92. Pamela Anny Marques da Silva
93. Pedro Coelho Terossi
94. Pedro Sobreira Soares
95. Phillipi Poloni
96. Rafael Santiago da Silva
97. Rafaela Gomes da Costa
98. Raissa Souza Santos
99. Raissa Toassa Martinelli
100. Raquel Germano Lopes
101. Raul Silva Ferreira
102. Renata Silva Fernandes dos Santos
103. Richard Christiano Batista Machado
104. Richard Miller de Souza
105. Rodolmo Inga Fragão José
106. Rodrigo Manoel Augusto
107. Rodrigo Marques Dias
108. Ryan Cesar Matos Barrozo
109. Ryan de Souza de Sá Barreto
110. Samuel David Tejera Salazar
111. Samuel Germiniani
112. Samuel Lucena Silva e Costa
113. Samuel Rodrigues da Silva
114. Sarah Roberta Felx dos Anjos
115. Sérgio Santos Silva Filho
116. Sofia Carnevalli Lopes
117. Sofia Gimenez Balistieri
118. Sulamita de Jesus Carvalho
119. Talita Lima
120. Tiago Yukio Horiuchi
121. Thiago Ramos Leite
122. Thiago Yuiti Azevedo Nakaba
123. Thomas Henrique de Souza Santos
124. Victor Gavazzi
125. Victor Samuel Mendes da Silva
126. Victor Soares Bou Assi Peric
127. Viktor Miranda
128. Vitor Daniel de Souza
129. Vinicius Eiki Venâncio Tanizaki
130. Vinicius Romão do Nascimento
131. Vithória Neves Garcia
132. Yasmim Jardim Amorim
133. Yasmin Faria dos Santos

Deixamos aqui um [vídeo](https://www.instagram.com/reel/DbJi3ppBLP5/?igsh=ZHVxM3NiZDBveHMz) produzido pelos alunos do curso de Engenharia de Transporte sobre o FTPA 2026. O vídeo mostrou o esforço e empenho dos alunos, professores e funcionários para a realização do evento.




fotos do evento
https://drive.google.com/drive/u/0/folders/1pwICG_EW39R5SrDwnb4xjUS6Ptz0_bwo
