---
title: Comissão organizadora
---

A comissão organizadora da FT de Portas Abertas 2026 foi instituída pelas portarias Portaria FT/DIR nº 4/2026, de de 13/04/2026, com os seguintes membros:

*Docentes:*

- Prof. Dr. Vitor Rafael Coluci (Presidente)

- Prof. Dr. André César Martins Cavalheiro

- Profa. Dra. Cláudia Vanessa dos Santos Correa

- Prof. Dr. Cristhof Johann Roosen Runge

- Profa. Dra. Eloisa Dezen-Kempter

- Prof. Dr. João Gilberto Mendes dos Reis

- Prof. Dr. Luís Augusto Angelotti Meira

- Prof. Dr. Luís Fernando de Avila

- Profa. Dra. Marta Siviero Guilherme Pires

- Prof. Dr. Murilo César Lucas

- Prof. Dr. Pedro Ivo Garcia Nunes

- Prof. Dr. Plínio Roberto Souza Vilela

- Prof. Dr. Vitor Eduardo Molina Junior

- Prof. Dr. William Machado Emiliano

- Prof. Dr. Yuri Alexandre Meyer

*Servidores técnico-administrativos:*

- Ádria Caloto de Oliveira

- Márcio Rogério de Moraes dos Santos

- Guilherme Henrique de Oliveira

- Patrícia Sacilotto Mercúrio

- Rodrigo Luiz Ximenes

- Ivonei Teixeira

*Discentes:*

- Ana Julia Vilas Boas

- Gabriel de Oliveira Pereira

- Gabriela Vieira Gonçalves

- Marcos Alexandre Barbosa

- Matheus Placideli Reghini Scola

- Murilo Bertolini Montoni

- Renata Silva Fernandes dos Santos

- Sofia Carnevalli Lopes

- Vinicius Eiki Venâncio Tanizaki